# Generated by Django 5.1.2 on 2024-11-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0006_interacoespessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
