# Generated by Django 5.1.2 on 2024-11-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0007_categoriadespesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='categoriadespesas',
            name='CategoriaPredefinida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primeiro_app.categoriapredefinida'),
            preserve_default=False,
        ),
    ]
