# Generated by Django 5.1.2 on 2024-11-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0008_categoriapredefinida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadespesas',
            name='CategoriaPredefinida',
        ),
        migrations.CreateModel(
            name='SelecionarCategoriaPre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoriaPredefinida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primeiro_app.categoriapredefinida')),
            ],
        ),
    ]
